### ISSUE TITLE
Need documentation for verifying extension is installed correctly.

### ISSUE THREAD

**Issue by shredmaster** [newrelic-experimental/newrelic-java-undertow#3]
[NOTE]: # ( ^^ Provide a general summary of the request in the title above. ^^ )

## Summary
I put the undertow-core-2.0.jar file in the *extensions* directory and restarted the server but I can't tell if it's installed correctly. I'm not seeing undertow traffic in the web transactions nor anything in the logs/newrelic_agent.log file. Can someone show me how to verify the extension is installed correctly?

## Possible Solution
The documentation should include information how to verify the extension is installed correctly.

**Comment by jmjava** [comment]
We are experiencing a similar issue - there does not appear to be any login and we cannot see any extra information in NR GUI

**Comment by dhilpipre** [comment]
Added comments to Getting Started section on verifying that the instrumentation was loaded
